### ISSUE TITLE
PIDS on Nano with ALTserial 

### ISSUE THREAD

**Issue by ClusterModzCo** [domnulvlad/KLineKWP1281Lib#4]
hi there ive been working with your program and library for a few days here and been having trouble with the readings. try the 01 connection test i got everything to work just fine using there ALTserial for nano but when going into reading measurements or single measurement is doesnt seem to follow true. when changing BLOCK_TO_READ ILL  normal can id is 0x42 for Control module voltage does not show. when i read into the https://www.blafusel.de/ for ids it says to use 66 for control module voltage but is still is not showing. ive tried 0x66 also just 42 and cant seem to get correct readings. would you please point me to what or how to fix this issue? i dont believe it has to do with the ALTSerial but im not going to say for certain. any help would be greatly appreciated thank you for you time and work!
![412714640_381508734446781_3898398326185172841_n](https://github.com/domnulvlad/KLineKWP1281Lib/assets/77478168/d0b44257-ba81-484a-b03f-a60af5fd05df)
![413447382_2231944407143719_4426143295173118493_n](https://github.com/domnulvlad/KLineKWP1281Lib/assets/77478168/35498890-b758-4bb2-a158-e958dfa7dfa5)

**Comment by domnulvlad** [comment]
Hi. First things first, this protocol isn't really about PIDs, instead it's blocks. Every block has between 0 and 4 values, whatever the module wants. Every module can have a maximum of 255 blocks which may or may not contain anything.

Every module is different, there is no real standard. This means your voltage value you are looking for could be anywhere.

You should try the "Full measurement test", and let it run until the end (block 255). Then you can look for the value you want to figure out what BLOCK_TO_READ and MEASUREMENT_TO_READ to use for the "Single measurement test".

**Comment by ClusterModzCo** [comment]
Okay that's fair and make sense to me and is that for every model let's say
that I am currently doing this on a 2003 Audi allroad Will that be true to
all 2003 Audi all roads or specifically this ECU ending in 551 aa ?

I figured as hooking up a OBD cable it reads VCDS so I assume that PIDs are
fairly the same for protocol is there not a way to read in that format?

**Comment by domnulvlad** [comment]
I am pretty sure it will be the same for all. Usually important values are kept in the same place for all models.

Since you have VCDS you can find this value easier. You can access the label files (or just open "Meas. Blocks") and find what "Group" (BLOCK_TO_READ) and what measurement (MEASUREMENT_TO_READ) you need. The first measurement is MEASUREMENT_TO_READ=0, the second is MEASUREMENT_TO_READ=1 etc..

**Comment by domnulvlad** [comment]
To clear things up:
This protocol has pretty much nothing in common with the standard OBD protocol and has nothing to do with CAN. There are no such things as PIDs.

For every included example you can select which module you want in the example's "configuration.h" by changing the connect_to_module (example: 0x01 = Engine, 0x02 = Auto Transmission, 0x17 = Instruments etc.).

If you have VCDS, the group/block and measurement correspond directly to what you can see in the "Meas. Blocks".

If you don't have VCDS, run the "03.Full_measurement_test" until the end (block 255) so you find what values all blocks contain.
For example, the RPM can appear in multiple places, you can use whichever one you want, they are all the same.
After you find a location for your value, you can try it in the "05.Single_measurement_test".
After you confirm it works, you can just use the readGroup() function with those numbers directly in your own sketch, as you can see in the example.

**Comment by domnulvlad** [comment]
Assuming I've cleared up the misunderstanding, I will close the issue.

**Comment by domnulvlad** [comment]
Assuming I've cleared up the misunderstanding, I will close the issue.
